import shutil
import sys, os
source_root = sys.argv[1]
for path in ["lib/src/library_err.c",
             "lib/src/library_file.c",
             "lib/src/library_utils.c",
             "lib/src/ccp4_array.c",
             "lib/src/ccp4_parser.c",
             "lib/src/ccp4_unitcell.c",
             "lib/src/cvecmat.c",
             "lib/src/cmtzlib.c",
             "lib/src/csymlib.c",
             "lib/src/ccp4_array.h",
             "lib/src/ccp4_sysdep.h",
             "lib/src/ccp4_errno.h",
             "lib/src/ccp4_parser.h",
             "lib/src/ccp4_spg.h",
             "lib/src/ccp4_utils.h",
             "lib/src/library_file.h",
             "lib/src/ccp4_types.h",
             "lib/src/ccp4_vars.h",
             "lib/src/cmtzlib.h",
             "lib/src/mtzdata.h",
             "lib/src/ccp4_unitcell.h",
             "lib/src/cvecmat.h",
             "lib/src/csymlib.h",
             "lib/src/ccp4_file_err.h",
             "lib/src/cmap_accessor.c",
             "lib/src/cmap_close.c",
             "lib/src/cmap_data.c",
             "lib/src/cmap_data.h",
             "lib/src/cmap_errno.h",
             "lib/src/cmap_header.c",
             "lib/src/cmap_header.h",
             "lib/src/cmap_labels.c",
             "lib/src/cmap_labels.h",
             "lib/src/cmap_open.c",
             "lib/src/cmap_skew.c",
             "lib/src/cmap_skew.h",
             "lib/src/cmap_stats.c",
             "lib/src/cmap_stats.h",
             "lib/src/cmap_symop.c",
             "lib/src/cmaplib.h",

             "lib/src/ccp4_diskio_f.c",
             "lib/src/ccp4_fortran.h",
             "lib/src/ccp4_general.c",
             "lib/src/ccp4_general.h",
             "lib/src/ccp4_general_f.c",
             "lib/src/ccp4_parser_f.c",
             "lib/src/ccp4_program.c",
             "lib/src/ccp4_program.h",
             "lib/src/ccp4_unitcell_f.c",
             "lib/src/cmaplib_f.c",
             "lib/src/cmaplib_f.h",
             "lib/src/cmtzlib_f.c",
             "lib/src/csymlib_f.c",
             "lib/src/library_f.c",

             "lib/data/symop.lib",
            ]:
  print path
  dir = os.path.split(path)[0]
  if (dir != "" and not os.path.isdir(dir)):
    os.makedirs(dir)
  open(path, "wb").write(open(os.path.join(source_root, path), "rb").read())
